const ObjectId = require("mongodb").ObjectId

const products = [
  {
    productName: "Nike dunk low",
    description: "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly shined overlays and classic team colors. With its iconic hoops design, the Nike Dunk Low channels '80s vintage back onto the streets while its padded, low-cut collar lets you take your game anywhere—in comfort.",
    size: "39",
    price: 200,
    //images: "http://dummyimage.com/166x100.png/cc0000/ffffff",
    rating: 4,
    reviewsNumber: 65,
    categoryId: ObjectId("6615401f37cf54d63c7d9476"),
  }, {
    productName: "Quechua Hiking Fleece Jacket",
    description: "This fleece jacket is ideal for hiking in cold weather. The stretch side inserts provide freedom of movement. The back opening improves ventilation for more comfort.",
    size: "M",
    price: 120,
    //images: "http://dummyimage.com/183x100.png/dddddd/000000",
    rating: 2,
    reviewsNumber: 59,
    categoryId: ObjectId("6615401f37cf54d63c7d9476"),
  }, {
    productName: "Short-Sleeved T-Shirt",
    description: "Our short-sleeve sports tee offers the perfect blend of comfort and functionality, ideal for all your athletic endeavors. Crafted from high-quality, breathable fabric with moisture-wicking technology, this tee keeps you cool and dry during workouts. Designed for performance, it provides a snug fit without restricting movement, ensuring freedom of motion. ",
    size: "XS",
    price: 30,
    //images: "http://dummyimage.com/146x100.png/dddddd/000000",
    rating: 5,
    reviewsNumber: 36,
    categoryId: ObjectId("6615401f37cf54d63c7d9476"),
  }, {
    productName: "Adidas leggings",
    description: "Elevate your workout wardrobe with our performance leggings, designed for ultimate comfort and support. Crafted from high-performance fabric with moisture-wicking technology, these leggings keep you dry and comfortable during intense workouts. Featuring a sleek and flexible design, our leggings offer a snug fit that moves with you, providing unrestricted movement for all your activities. Whether you're hitting the gym or going for a run, these leggings are your perfect companion.",
    size: "S",
    price: 45,
    //images: "http://dummyimage.com/176x100.png/cc0000/ffffff",
    rating: 5,
    reviewsNumber: 45,
    categoryId: ObjectId("6615401f37cf54d63c7d9476"),
  }, {
    productName: "Water bottle",
    description: "Stay hydrated on the go with our sports water bottle, the perfect companion for your active lifestyle. Made from durable and lightweight materials, this bottle is designed to withstand the rigors of your workouts and outdoor adventures.",
    size: "No size",
    price: 20,
    //images: "http://dummyimage.com/220x100.png/cc0000/ffffff",
    rating: 1,
    reviewsNumber: 40,
    categoryId: ObjectId("6615401f37cf54d63c7d9476"),
  }, {
    productName: "New balance sneakers",
    description: "Featuring a sleek design and durable construction, our sneakers offer stability and traction for every stride. With a lightweight feel and responsive cushioning, they keep you agile and ready to tackle any activity.",
    size: "37",
    price: 147,
    //images: "http://dummyimage.com/149x100.png/cc0000/ffffff",
    rating: 4,
    reviewsNumber: 27,
    categoryId: ObjectId("6615401f37cf54d63c7d9476"),
  }, {
    productName: " Training top",
    description: "Elevate your training sessions with our performance-driven training top, designed for optimal comfort and flexibility. Crafted from moisture-wicking fabric, this top keeps you cool and dry, allowing you to focus on your workout.",
    size: "S",
    price: 24,
    //images: "http://dummyimage.com/245x100.png/cc0000/ffffff",
    rating: 5,
    reviewsNumber: 23,
    categoryId: ObjectId("6615401f37cf54d63c7d9476"),
  }, {
    productName: "Skiing gloves",
    description: "Featuring insulation and a snug fit, our gloves provide exceptional warmth without compromising on flexibility, allowing you to maintain precise control of your ski poles. The adjustable wrist straps ensure a secure fit, while the reinforced palms offer enhanced grip and durability.",
    size: "No size",
    price: 15,
    //images: "http://dummyimage.com/180x100.png/cc0000/ffffff",
    rating: 2,
    reviewsNumber: 63,
    categoryId: ObjectId("6615401f37cf54d63c7d9476"),
  }, {
    productName: "Womens jacket",
    description: "Conquer the elements in style with our performance jacket, engineered to keep you warm and dry during outdoor workouts. Crafted from weather-resistant materials, this jacket offers protection from wind and rain without sacrificing breathability.2",
    size: "XL",
    price: 120,
    //images: "http://dummyimage.com/170x100.png/cc0000/ffffff",
    rating: 4,
    reviewsNumber: 37,
    categoryId: ObjectId("6615401f37cf54d63c7d9476"),
  }
]

module.exports = products